models/rues.php
<?php
namespace app\models;

use app\models\entities\Company;
use yii\base\Model;

class rues extends Model
{
    public $campo;
    public $verif;

    public function rules()
    {
        return[
            [['campo','verif'],'required','message'=>'El {attribute} es requerido'],
            ['campo', 'integer', 'message' => 'Sólo números enteros'],
            [['campo'],'match','pattern'=>'/^.{3,14}$/','message'=>'El numero de registro debe tener minimo 3 caracteres y maximo 14'],
            ['verif', 'integer', 'message' => 'Sólo números enteros'],
            [['verif'],'match','pattern'=>'/^.{1,1}$/','message'=>'El codigo de verificacion solo es de un digito'],
            [['verif','campo'],'safe'],
            [['campo'],'unique','targetClass'=>Company::className(),'targetAttribute'=>'nit']
        ];
    }

    public function attributeLabels()
    {
        return [
            'verif' => 'Digito de verificación',
            'campo' => 'Número único tributario'
        ];
    }
}

controllers/RuesController.php
<?php
namespace app\controllers;

use app\models\editarinfoForm;
use app\models\entities\Company;
use Yii;
use app\components\BaseController;
use app\models\rues;
use app\models\editarinfo;
use yii\helpers\VarDumper;
use yii\httpclient\Client;
use app\models\empresa;

class RuesController extends BaseController {



    public function actionEnviarDatos()
    {
        $rtaRUES[] = $this->actionCrearempresa();
        $this->actionEmpresa($rtaRUES[]);
    }

    public function actionCrearempresa() {
        //si esta logueado lo redirige al home del proyecto.
        if(!Yii::$app->user->isGuest)
            return $this->goHome();

        $Modato = false;
        $model = new rues();
        $respuesta=[];
        if ($model->load(Yii::$app->request->post()) and $model->validate()) {
            $ClienteRues = new Client();
            $responseToken = $ClienteRues->createRequest()->setMethod('POST')->setUrl(\Yii::$app->params['UrlToken'])->setData(\Yii::$app->params['RUESAccessInfo'])->send();
            if ($responseToken->isOk) {
                $data = \Yii::$app->params['UrlConsultaNit'] . "?usuario=" . \Yii::$app->params['RUESAccessInfo']['Username'] . "&nit=" . $model->campo . "&dv=". $model->verif;
                $token = $responseToken->data['token_type'] . " " . $responseToken->data['access_token'];
                $respuestaNit = $ClienteRues->createRequest()->setMethod('POST')->setUrl($data)->setHeaders(['Authorization' => $token])->send();
                if (!isset($respuestaNit->data['error']))
                {
//                    VarDumper::dump($respuestaNit,10,1);exit;//TODO *imprime todos los Datos que trae RUES*
                    foreach ($respuestaNit->getData()['registros'] as $value) {
                        $respuesta['razon_social'] = $value['razon_social'];
                        $respuesta['tipo_identificacion'] = $value['tipo_identificacion'];
                        $respuesta['numero_identificacion'] = $value['numero_identificacion'];
                        $respuesta['estado_matricula'] = $value['estado_matricula'];
                        $respuesta['matricula'][] = $value['matricula'];
                        if(isset($value['establecimientos']) and is_array(isset($value['establecimientos'])) and count($value['establecimientos'])>0)
                        {
                            $respuesta['correo_electronico_fiscal'] = $value['establecimientos'][0]['correo_electronico_fiscal'];
                            $respuesta['direccion_fiscal'] = $value['establecimientos'][0]['direccion_fiscal'];
                        }
                        if(isset($value['telefono_fiscal_1']))
                        {
                            $respuesta['telefono_fiscal_1'] = $value['telefono_fiscal_1'];
                        }
                        $estado = 'CANCELADA';
                        if($respuesta['estado_matricula'] != $estado){
                            if (!is_null($respuesta['matricula']) and !empty($respuesta['matricula']))
                            {
                                $Modato = true;
                            }else{
                                $Modato = false;
                            }
                        }
                        else
                        {
                            Yii::$app->session->setFlash('error', "La matricula mercantil para esta empresa se encuentra Cancelada.");
                        }
                    }
                    Yii::$app->session->set('infoRues', $respuesta);
                }
                else
                {
                    Yii::$app->session->setFlash('error', "Numero Único Tributario no retorna busqueda.");
                }
            }else{
                echo "error (" . $responseToken->data['error_description'] . ")";
            }
        }
        return $this->render('crearempresa', ['model' => $model, 'supuesto'=>$Modato, 'data'=>$respuesta]);
    }

    public function actionEmpresa(){
        $model = new empresa();
        if ($model->load(Yii::$app->request->post()) and $model->validate()){
            $model->password = password_hash($model->password, PASSWORD_DEFAULT);
                if($model->save()){
                    Yii::$app->session->setFlash('success', "Empresa y Representante legal Creados Correctamente, Para el ingreso al aplicativo, Use su correo ");
                    return $this->redirect(["site/index"]);
                }
        }
        return $this->render('empresa',['model'=>$model]);
    }


    public function actionEditarinfo() {
        $model = new editarinfoForm();
        switch (Yii::$app->request->post('dato'))
        {
            case "A":
                $datosA = Company::find()->select('name, nit, phone, address, email ')->where('nit = :nit')->params([':nit'=>Yii::$app->request->post('buscar')])->one();
                VarDumper::dump($datosA,10,1);
                break;
            case "B":
                $datosB = Company::find()->select('name, nit, phone, address, email ')->where(['name = :name'])->params([':name'=> $model->combo])->all();
                break;
            default:
                break;
        }
        return $this->render('editarinfo',['model'=>$model]);
    }
}

views/rues/crearempresa.php
<?php
    /* @var $model app\models\rues  */
    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
    use yii\bootstrap\Modal;
    use yii\web\View;

    if($supuesto){
        $script = <<< JS
        $("#Correcto").modal("show");
JS;
        $this->registerJs($script, View::POS_END);
    }
?>

<h1>Verificar NIT.</h1>
<div id='div-alfa' class='preloader-alfa'></div>
<?php $form = ActiveForm::begin(['method'=>'POST']);?>
<?= Html::errorSummary($model,['class'=>'alert alert-block alert-danger']) ?>
<div><br />
    <table class="table table-borderless table-responsive-lg">
        <tr>
            <th><?= $form->field($model, 'campo')->textInput(['placeholder' => $model->getAttributeLabel('campo'),'maxlength'=>14,'class'=>'form-control'])?></th>
            <th><?= $form->field($model, 'verif')->textInput(['placeholder' => $model->getAttributeLabel('verif'),'maxlength'=>1])?></th>
        </tr>
    </table>
    <?= Html::submitButton("Verificar", ['onclick' => '$("#div-alfa").slideDown("fast")',"class" => "btn btn-success"]) ?>
</div>
<?php ActiveForm::end();?>

<?php
Modal::begin([
    'id'=>'Correcto',
    'header' => 'Datos empresa'
]);
if($data != array()):
?>
    <div><div>
        <label>El <?= $data['tipo_identificacion']." ".$data['numero_identificacion'] ?> corresponde a <?=$data['razon_social']?>.</label><br /><br />
        <label>¿Estos datos Son Correctos?</label>
    </div><br /><br /><br />
    <div align='right'>
        <?= Html::a('Si.',['/rues/empresa'],['class'=>'btn btn-primary btn-success'])?>
        <!--            La Url aparecia en get por la variable que estaba enviando desde la linea de encima-->
        <button class='btn btn-primary btn-info' data-dismiss="modal">No.</button>
    </div></div>
<?php
endif;
Modal::end();
?>

views/rues/editarinfo.php
<?php
/* @var $model app\models\editarinfoForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<div>
    <h1>Actualizar datos.</h1>
    <?php $form = ActiveForm::begin()?>
    <?= Html::errorSummary($model,['class'=>'alert alert-block alert-danger']) ?>

        <div class="form-inline align-items-center">
            <div class="col-auto">
                <select name="dato">
                    <option value="">Metodo de Busqueda</option>
                    <option value="A">Nit.</option>
                    <option value="B">Nombre empresa.</option>
                </select>

            </div>
            <div class="col-auto">
                <?= $form->field($model, 'buscar')->textInput(['placeholder' => $model->getAttributeLabel('buscar'),'class'=>'form-control mb-2'])?>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-2">Buscar.</button>
            </div>
        </div>
    <div class="form-group">
        <br>
        <br>
        <?= $form->field($model, 'nomemp')->textInput(['placeholder' => $model->getAttributeLabel('nomemp'),'disabled'=>'disabled'])?>
        <br>
        <?= $form->field($model, 'numide')->textInput(['placeholder' => $model->getAttributeLabel('numide'),'disabled'=>'disabled'])?>
        <br>
        <?= $form->field($model, 'telef')->textInput(['placeholder' => $model->getAttributeLabel('telef')])?>
        <br>
        <?= $form->field($model, 'dirrec')->textInput(['placeholder' => $model->getAttributeLabel('dirrec')])?>
        <br>
        <?= $form->field($model, 'emai')->textInput(['placeholder' => $model->getAttributeLabel('emai')])?>
    </div>
    <button type="submit" class="btn btn-primary">Guardar.</button>
    <?php ActiveForm::end();?>
</div>

views/rues/empresa.php
<?php
/* @var $model app\models\empresa */

    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
?>

<div>
    <h1>Datos Empresa.</h1>
    <?php $form = ActiveForm::begin(['method'=>'POST']);?>
    <?= Html::errorSummary($model,['class'=>'alert alert-block alert-danger']) ?>
    <div class="form-group">
        <?= $form->field($model, 'nomemp')->textInput(['placeholder' => $model->getAttributeLabel('nomemp'),'disabled'=>'disabled'])?>
        <br>
        <?= $form->field($model, 'numide')->textInput(['placeholder' => $model->getAttributeLabel('numide'),'disabled'=>'disabled'])?>
        <br>
        <?= $form->field($model, 'matricula')->textInput(['placeholder' => $model->getAttributeLabel('matricula')])?>
        <br>
        <?= $form->field($model, 'telef')->textInput(['placeholder' => $model->getAttributeLabel('telef')])?>
        <br>
        <?= $form->field($model, 'dirrec')->textInput(['placeholder' => $model->getAttributeLabel('dirrec')])?>
        <br>
        <?= $form->field($model, 'emai')->textInput(['placeholder' => $model->getAttributeLabel('emai')])?>
        <br><br>
        <h1>Datos Representante.</h1>
        <br><br>
        <?= $form->field($model, 'name')->textInput(['placeholder' => $model->getAttributeLabel('name')])?>
        <br>
        <?= $form->field($model, 'lastname')->textInput(['placeholder' => $model->getAttributeLabel('lastname')])?>
        <br>
        <?= $form->field($model, 'username')->textInput(['placeholder' => $model->getAttributeLabel('username')])?>
        <br>
        <?= $form->field($model, 'password')->passwordInput(['placeholder' => $model->getAttributeLabel('password')])?>
        <br>
        <?= $form->field($model, 'verif')->passwordInput(['placeholder' => $model->getAttributeLabel('verif')])?>
        <br />
        <p>Manifiesto que he leído y al hacer click en registrar, acepto la política de privacidad y protección de datos personales adoptada por el Instituto Colombiano Agropecuario – ICA y publicada para consulta en la página web <a href="https://www.ica.gov.co" target="_blank">https://www.ica.gov.co </a> Para lo cual autorizo a que el ICA pueda tratar datos personales conforme dicha política y en los términos en que ello sea necesario.</p>
        <br />
        <?= Html::submitButton("Guardar.", ["class" => "btn btn-primary"]) ?>
    </div>
    <?php ActiveForm::end();?>
</div>