controllers/PruebaController.php
<?php

namespace app\controllers;

use app\models\entities\Company;
use app\models\entities\UserCompany;
use app\models\entities\Users;
use Yii;
use app\models\forms\crearusuempForm;
use app\models\forms\inhabilitarusuempForm;
use app\models\forms\registrousuemp;
use app\models\forms\mistareasForm;
use app\components\BaseController;
use yii\data\ActiveDataProvider;
use yii\helpers\Json;
use yii\helpers\VarDumper;
use yii\web\User;


class PruebaController extends BaseController

{
    public function actionCrearusuemp()
    {

        $usuario = UserCompany::find()->where("id_user = :idus")->params([':idus' => Yii::$app->user->identity->idusers])->one();
        Yii::$app->session->set("idcompania", $usuario->id_company);

        $model = new crearusuempForm();
        $boolean = false;


        if ($model->load(Yii::$app->request->post()) and $model->validate()) {
            if ($model->cantidadmaximausuarios() < 3 and $model->save()) {
                $boolean = true;
                $model = new crearusuempForm();
            } else {
                Yii::$app->session->setFlash('success', 'Ya se ingresaron la cantidad maxima de usuarios con exito!!');
                return $this->redirect(["/"]);
            }
        }

        return $this->render('crearusuemp', ['model' => $model, 'registro_otro' => $boolean,]);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionRegistrousuemp()
    {
        $model = new registrousuemp();

        if ($model->load(Yii::$app->request->post()) and $model->validate()) {
            $model->password = password_hash($model->password, PASSWORD_BCRYPT);

//            $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
           if($model->save())
           {
               Yii::$app->mailer->compose()
                   ->setTo($model->username)
                   ->setFrom('Notificaciones@ica.gov.co')
                   ->setSubject('Usuario Registrado')
                   ->setHtmlBody('<html><body>Buen día.<br /><br />Apreciado Usuario.<br /><br />Su usuario a sido regisrtado correctamente, para el ingreso use el siguiente enlace http://192.168.1.24/siria/web/<br /><br />Muchas gracias por su colaboración</body></html>')
                   ->send();
                Yii::$app->session->setFlash("success",'Excelente');
                return $this->redirect(["site/index"]);
           }
       }
        return $this->render('registrousuemp', ['model' => $model]);
    }

    public function actionInhabilitarusuemp()
    {
        $UsuarioLogueado = Yii::$app->user->identity;
        $usuarios = Users::find()->joinWith(['userCompany', 'userCompany.company'])
            ->where(['user_company.id_company' => $UsuarioLogueado->userCompany->id_company]);

        $dataProvider = new ActiveDataProvider([
            'query' => $usuarios,
            'pagination' => [
                'pageSize' => 15
            ],
            'sort' => [
                'defaultOrder' => ['name' => SORT_ASC]
            ]
        ]);

        return $this->render('inhabilitarusuemp', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * @todo Hacer la funcion de cambio para los estados de los usuarios
     */
        public function actionCambioestadousuemp(){
            if(Yii::$app->request->post('id') != Yii::$app->user->id)
            {
                $Usercompany = UserCompany::find()->where(['id_user'=>Yii::$app->request->post('id')])->one();
                $Usercompany->Estado_usuario = !$Usercompany->Estado_usuario?1:0;
                echo Json::encode(['status'=>'success','message'=>'','value'=>Yii::$app->request->post('id')]);
                $Usercompany->save();
            }
            else
            {
                echo Json::encode(['status'=>'error','message'=>'No se puede inhabilitar el usuario logueado','value'=>Yii::$app->request->post('id')]);
            }
        }

    /**
     * @todo funcion para mostrar como se se ejecuta la cortina del ica
     **/
    public function actionCortina()
    {
        return $this->render("cortina");
    }

    public function actionMistareas()
    {
        return $this->render('mistareas');
    }
}

views/prueba/cortina.php
<?php
use yii\helpers\Html;
?>

<div id='div-alfa' class='preloader-alfa'></div>
<div class="container">
	<?php echo Html::button("muestra cortina",['onclick' => '$("#div-alfa").slideDown("fast")'])?>
</div>

views/prueba/crearusuemp.php
<?php

/* @var $model app\models\forms\crearusuempForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;
use yii\web\View;

if($registro_otro)
{
$script = <<< JS
     $("#confirma-otro").modal("show");
JS;
$this->registerJs($script, View::POS_END);    
}
?>

<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<main class="one">
    <div></div>
    
 <div>
     
     <h1><i class="fa fa-users" aria-hidden="true"></i></h1>
  
     <h2>Registro funcionarios delegados</h2> 
     <br>
<?php $form = ActiveForm::begin(['id' => 'crear-form']); ?>
<?= $form->errorSummary($model)?>

    <?= $form->field($model, 'name')->textInput(['maxlength'=>60,'placeholder'=>'Nombre del funcionario']) ?>
     <?= $form->field($model, 'lastname')->textInput(['maxlength'=>60,'placeholder'=>'Apellido del funcionario']) ?>
    <?= $form->field($model, 'username')->textInput(['maxlength'=>60,'autofocus' => true,'placeholder'=>'Correo institucional']) ?>
  
<?= Html::submitButton('Guardar', ['class' => 'btn btn-success', 'name' => 'login-button']) ?>

     <br>     
     <?php ActiveForm::end(); ?>
     <br>

     
</div>
    
</main>

<?php 
Modal::begin([
    'id'=>'confirma-otro',
    'header' => 'Confirmación',   
    'footer'=> Html::button("Aceptar",["class"=>"btn btn-success","data-dismiss"=>"modal"])." ".Html::a("Continuar","/siria/web/site/index",["class"=>"btn btn-info",])
]);

echo '¿Desea guardar otro usuario?';

Modal::end();



?>

views/prueba/inhabilitarusuemp.php
<?php
/* @var $model app\models\forms\inhabilitarusuempForm */
/* @var $dataProvider \yii\data\ActiveDataProvider */
use yii\grid\GridView;
use yii\helpers\Url;
use yii\web\View;

$url =  Url::to(['prueba/cambioestadousuemp'], 'http');
$javascript = <<<JS
function change(check)
{
    var keys = $('#usuarios').yiiGridView('getSelectedRows');
    if(keys.length>3)
        {
            event.preventDefault();
            alert('No puede habilitar mas de 3 usuarios');
            return;
        }
    
    $.ajax({
        url : '$url',
        data : { id : $(check).val() },
        type : 'POST',
        dataType : 'json',
        
        success : function(json){
            if(json.status=='error')
                {
                    $("input[value='"+json.value+"']").prop("checked","true");
                    alert(json.message);
                }else{
                    alert('Se realizo el cambio de estado');
                }
        }
    })
}
JS;

$this->registerJs($javascript,View::POS_END,'change');


?>
<h1></h1>
<?= GridView::widget([
    'id' => 'usuarios',
        'dataProvider' => $dataProvider,
        'columns' =>[
            [
                'attribute'=>'name',
                'header' => 'Nombre'
            ],
            [
                'attribute'=>'lastname',
                'header' => 'Apellido'
            ],
            [
                'class' => 'yii\grid\CheckboxColumn',
                'header'=>'Habilitado',
                'checkboxOptions' => function ($model) {
                    return ['onClick'=>'change(this)','checked' => ($model->userCompany->Estado_usuario==1)?true:false];
                }

            ],
        ]
]);
?>

views/prueba/mistareas.php
<?php

/* @var $model app\models\forms\mistareasForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>


<h2> Mis tareas asignadas </h2>



<?php $form= ActiveForm::begin([]);?>
    <div class="input-group mb-3 " >
        <table class="table">
            <tr><td>
                </td></tr>
<tr><td>
        <label>Estados tareas</label>
        <select class="table table-striped form-control">
                    <option value = "0"></option>
                    <option value = "1">Pendiente</option>
                    <option value = "2">Realizada</option>
                </select>
</td></tr>

    </table>
    </div>
<br>
<?= Html::submitButton('Buscar Solicitud', ['class'=>'btn btn-success','name' => 'login-button','redirect'=>"/siria/web/site/index"]) ?>
    <?php ActiveForm::end(); ?>

views/prueba/registrousuemp.php
<?php

/* @var $model app\models\forms\registrousuemp */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<main class="one">
    <h1><i class="fa fa-user" aria-hidden="true"></i></h1>

    <div>

        <fieldset>
            <?php $form = ActiveForm::begin(['id' => 'registrousuemp-form',
                'fieldConfig' => ['errorOptions' => ['class' => 'help-block', 'encode' => false]]
            ]); ?>
            <?= $form->errorSummary($model)?>
            <?= $form->field($model, 'name')->textInput(['maxlength'=>60,'placeholder'=>'Nombre del usuario']) ?>
            <?= $form->field($model, 'lastname')->textInput(['maxlength'=>30,'placeholder'=>'Apellidos del usuario']) ?>
            <?= $form->field($model, 'username')->textInput(['maxlength'=>30,'placeholder'=>'Correo del usuario']) ?>
            <?= $form->field($model, 'password')->passwordInput(['maxlength'=>15,'placeholder'=>'Contraseña']) ?>
            <?= $form->field($model, 'confirmar')->passwordInput(['maxlength'=>15,'placeholder'=>'Confirmar contraseña']) ?>
            <?= $form->field($model, 'random')->textInput(['maxlength'=>11,'placeholder'=>'Codigo de verificacion']) ?>
            <fieldset/>
            <p>Manifiesto que he leído y al hacer click en registrar, acepto la política de privacidad y protección de datos personales adoptada por el Instituto Colombiano Agropecuario – ICA y publicada para consulta en la página web <a href="https://www.ica.gov.co" target="_blank"> https://www.ica.gov.co.</a> Para lo cual autorizo a que el ICA pueda tratar mis datos personales conforme dicha política y en los términos en que ello sea necesario.</p>
            <?= Html::submitButton('Registrar', ['class'=>'btn btn-success','name' => 'login-button']) ?>
            <?php ActiveForm::end(); ?>

    </div>

</main>