controllers/SiteController.php
<?php
namespace app\controllers;

use app\models\entities\UserCompany;
use app\models\entities\Users;
use Yii;
use yii\helpers\VarDumper;
use yii\web\Response;
use app\models\forms\LoginForm;
use app\components\BaseController;
use yii\web\Session;
use app\models\forms\FormRecoverPass;
use app\models\forms\FormResetPass;


class SiteController extends BaseController
{
    public function actionRecoverpass()
    {
        $model = new FormRecoverPass;
        if ($model->load(Yii::$app->request->post()))
        {
            if ($model->validate())
            {
                if($model->recuperar())
                {
                    return $this->redirect(["site/resetpass"]);
                }
            }
            else
            {
                $model->getErrors();

            }
        }
        return $this->render("recoverpass", ["model" => $model]);
    }

    public function actionResetpass()
    {
        $model = new FormResetPass();
        if ($model->load(Yii::$app->request->post()))
        {
            if ($model->validate())
            {
                if($model->cambiar())
                {
                    return $this->redirect(["site/login"]);
                }
            }
            else
            {
                $model->getErrors();
            }
        }
        return $this->render("resetpass", ["model" => $model]);
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        /*if(!Yii::$app->user->isGuest)
        {
            return $this->render('index');
        }
        else
        {
            $this->redirect(['login']);
        }*/
        return $this->render('index');

    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $this->layout = 'login';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="container-fluid main-bg-landing">
    <br /><h1 class="text-center">Bienvenidos a S.I.R.I.A</h1><h4 class="text-center">Sistema de Información para el Reporte de Insumos Agrícolas.</h4><br /><br />
    <div class="row">
        <div class="col-lg-4">
            <h2 class="text-center">Plaguicida</h2>
            <p class="text-center"><a class="btn btn-default btn-success" href="https://www.ica.gov.co/areas/agricola/servicios/regulacion-y-control-de-plaguicidas-quimicos.aspx" target="_blank">Descripción &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <h2 class="text-center">Bioinsumos</h2>
            <p class="text-center"><a class="btn btn-default btn-success" href="https://www.ica.gov.co/preguntas-frecuentes/agricola/bioinsumos"  target="_blank">Descripción &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <h2 class="text-center">Fertilizantes</h2>
            <p class="text-center"><a class="btn btn-default btn-success" href="https://www.ica.gov.co/getdoc/a5c149c5-8ec8-4fed-9c22-62f31a68ae49/fertilizantes-y-bio-insumos-agricolas.aspx"  target="_blank">Descripción  &raquo;</a></p>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid main-bg-landing">
    <div class="row vertical-offset-100">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default center-block">
                <div class="panel-heading center-block">
                    <?= Html::encode($this->title) ?>
                </div>
                <div class="panel-body">
                    <?= Html::beginForm() ?>
                    <fieldset>
                        <?= Html::errorSummary($model,['class'=>'alert alert-block alert-danger']) ?>
                        <?= Html::activeTextInput($model,'username',['placeholder' => 'Usuario','autocomplete'=>'off','autofocus' => true,'class'=>'form-control'])?>
                        <br>
                        <?= Html::activePasswordInput($model,'password',['placeholder' => 'Contraseña','autocomplete'=>'off','class'=>'form-control']) ?>
                        <br><br>
                            <?= Html::submitButton('Ingresar', ['class' => 'btn btn-lg btn-success btn-block', 'name' => 'login-button', 'id'=>"login"]) ?>
                        <br>
                    </fieldset>
                    <?= Html::endForm() ?>
                    <h5 class="text-center">¿Olvidó su contraseña?</h5>
                    <?= Html::a('Recuperar Contraseña',['site/recoverpass'],['class'=>'btn btn-lg btn-success btn-block']) ?>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/recoverpass.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h1>Recuperar Contraseña</h1>
<?php $form = ActiveForm::begin([
    'method' => 'post',
    'enableClientValidation' => true,
]);
?>

<div class="form-group">
    <?= $form->field($model, "username")->input("email") ?>
</div>

<?= Html::submitButton("Recuperar.", ["class" => "btn btn-success"]) ?>

<?php $form->end() ?>

views/site/resetpass.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<h1>Recuperar Contraseña</h1>
<?php $form = ActiveForm::begin(['method' => 'post']);?>
<div class="form-group"><?= $form->field($model, "email")->input("email") ?></div>

<div class="form-group"><?= $form->field($model, "password")->input("password") ?></div>

<div class="form-group"><?= $form->field($model, "password_repeat")->input("password") ?></div>

<div class="form-group"><?= $form->field($model, "verification_code")->input("text") ?></div>

<?= Html::submitButton("Recuperar Contraseña", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>